server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Single Page Application routing fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API proxy
    location /api/ {
        proxy_pass http://sindio-core:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
